[[main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = 1

[[main]]
    name = "Sections"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 3

[[main]]
    name = "Webhosting"
    url = "/webhosting/"
    parent = "Sections"

[[main]]
    name = "Python"
    url = "/python/"
    parent = "Sections"

[[main]]
    name = "Linux"
    url = "/Linux/"
    parent = "Sections"

[[main]]
    name = "Social"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 4

[[main]]
    name = "Github"
    url = "https://github.com/Ferratauris"
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "Twitch"
    url = "https://www.twitch.tv/ferratauris"
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "Twitter"
    url = "https://twitter.com/Ferratauris"
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "YouTube Channels"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 6
    
[[main]]
    name = "The Business"
    url = "https://www.youtube.com/channel/UCPcgkQFpd_pEIwScIZpZeAQ"
    hrefTargetBlank = true
    parent = "YouTube Channels"
