[[main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = 1

[[main]]
    name = "Sections"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 3

[[main]]
    name = "Web Development"
    url = "/posts/tests/"
    parent = "Sections"

[[main]]
    name = "Social"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 4

[[main]]
    name = "Github"
    url = ""
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "Twitch"
    url = ""
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "Twitter"
    url = ""
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "YouTube Channels"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 6
    
[[main]]
    name = ""
    url = ""
    hrefTargetBlank = true
    parent = "YouTube Channels"